---
- name: Bandwidth Test from MikroTik and Save Results
  hosts: all
  connection: network_cli
  gather_facts: no
  vars:
    timestamp: "{{ lookup('pipe', 'TZ=Asia/Jakarta date +\"%Y-%m-%d %H:%M:%S %Z\"') }}"
    current_date: "{{ lookup('pipe', 'TZ=Asia/Jakarta date +\"%Y-%m-%d\"') }}"
    routers:
      "172.31.254.36":
        csv_file: "./result_router1_{{ current_date }}.csv" #Sesuaikan path dan format nama report router core 1 yang diinginkan
        site_file: "./sites_router1.csv" #Sesuaikan path client sites router core 1 yang dituju
      "172.31.254.37":
        csv_file: "./result_router2_{{ current_date }}.csv" #Sesuaikan path dan format nama report router core 2 yang diinginkan
        site_file: "./sites_router2.csv" #Sesuaikan path client sites router core 2 yang dituju

  tasks:
    - name: Set CSV and site file paths dynamically based on hostname
      set_fact:
        csv_filename: "{{ routers[inventory_hostname].csv_file }}"
        site_file: "{{ routers[inventory_hostname].site_file }}"

    - name: Ensure CSV file with header exists
      lineinfile:
        path: "{{ csv_filename }}"
        line: "Timestamp, Nama site, IP Address, TX Total Average, RX Total Average, Status Average"
        create: yes
        insertafter: EOF
      when: not lookup('file', csv_filename, errors='ignore')

    - name: Read Input Client Sites
      read_csv:
        path: "{{ site_file }}"
      register: csv_data

    - name: Run bandwidth test for each client site
      routeros_command:
        commands: "/tool bandwidth-test address={{ item.site_ip }} protocol=tcp direction=both user={{ item.site_user }} password={{ item.site_pass }} duration=10s"
      with_items: "{{ csv_data.list }}"
      register: bandwidth_test_output
      ignore_errors: yes

    - name: Write raw bandwidth test results to file
      copy:
        content: "{{ item.stdout }}"
        dest: "/tmp/bandwidth_test_raw_results_{{ inventory_hostname }}_{{ item.item.site_ip }}.txt"
      with_items: "{{ bandwidth_test_output.results }}"
      when: item.stdout is defined

    - name: Initialize averages list
      set_fact:
        averages: []

    - name: Extract TX and RX averages for each site
      set_fact:
        averages: "{{ averages + [{'site_name': item.item.site_name, 'site_ip': item.item.site_ip, 'tx_average': item.stdout | regex_findall('tx-total-average:\\s*([0-9.]+[A-Za-z]+)') | last | default('N/A'), 'rx_average': item.stdout | regex_findall('rx-total-average:\\s*([0-9.]+[A-Za-z]+)') | last | default('N/A'), 'status_average': item.stdout | regex_findall('status:\\s*([A-Za-z ]+)') | last | default('N/A') } ] }}"
      loop: "{{ bandwidth_test_output.results }}"
      when: item.stdout is defined

    - name: Append results to CSV
      lineinfile:
        path: "{{ csv_filename }}"
        line: "{{ timestamp }},{{ item.site_name }},{{ item.site_ip }},{{ item.tx_average }},{{ item.rx_average }},{{ item.status_average }}"
      with_items: "{{ averages }}"
