---
- name: Bandwidth Test from MikroTik and Save Results
  hosts: all #Setting router hosts
  connection: network_cli
  gather_facts: no
  tasks:
    - name: Initialize timestamp variable #Pengambilan timestamp untuk variabel report di dalam csv output file
      set_fact:
        current_timestamp: "{{ lookup('pipe', 'TZ=Asia/Jakarta date +\"%Y-%m-%d %H:%M:%S %Z\"') }}"

    - name: Get current date for filename #Pengambilan tanggal untuk penamaan file report csv perhari
      set_fact:
        current_date: "{{ lookup('pipe', 'TZ=Asia/Jakarta date +\"%Y-%m-%d\"') }}"

    - name: Set Output CSV filename for routercore 1 #Penamaan file CSV
      set_fact:
        csv_filename_rc1: "./result_router1_{{ current_date }}.csv"

    - name: Set Output CSV filename for routercore 2 #Penamaan file CSV
      set_fact:
        csv_filename_rc2: "./result_router2_{{ current_date }}.csv"

    - name: Check if the CSV file exists #Mengecek ketersediaan untuk report file
      stat:
        path: "{{ csv_filename_rc1 }}"
      register: csv_file_stat_rc1

    - name: Check if the CSV file exists #Mengecek ketersediaan untuk report file
      stat:
        path: "{{ csv_filename_rc2 }}"
      register: csv_file_stat_rc2

    - name: Add CSV header if file does not exist rc1  #Menambahkan header pada file csv
      lineinfile:
        path: "{{ csv_filename_rc1 }}"
        line: "Timestamp, Nama site, IP Address, TX Total Average, RX Total Average, Status Average"
        create: yes
        insertafter: EOF
      when: not csv_file_stat_rc1.stat.exists

    - name: Add CSV header if file does not exist rc2  #Menambahkan header pada file csv
      lineinfile:
        path: "{{ csv_filename_rc2 }}"
        line: "Timestamp, Nama site, IP Address, TX Total Average, RX Total Average, Status Average"
        create: yes
        insertafter: EOF
      when: not csv_file_stat_rc2.stat.exists

    - name: Read Input Client Sites RC1 #Membaca file csv berisi info client site
      read_csv:
        path: ./sites_router1.csv
      register: csv_data_rc1
      when: inventory_hostname == '172.31.254.36'

    - name: Read Input Client Sites RC2 #Membaca file csv berisi info client site
      read_csv:
        path: ./sites_router2.csv
      register: csv_data_rc2
      when: "'172.31.254.37' in inventory_hostname"

    - name: Run bandwidth test from Router Core 1 #Menjalankan tes bw dari router core
      when: "'172.31.254.36' in inventory_hostname"
      routeros_command:
        commands: "/tool bandwidth-test address={{ item.site_ip }} protocol=tcp direction=both user={{ item.site_user }} password={{ item.site_pass }} duration=10s"
      register: bandwidth_test_output_rc1
      with_items: "{{ csv_data_rc1.list }}" #Mengambil variabel data dari file input client sites
      ignore_errors: yes #Apabila error/client sites rto, tetap berjalan untuk test client sites berikutnya

    - name: Run bandwidth test from Router #Menjalankan tes bw dari router core
      when: "'172.31.254.37' in inventory_hostname"
      routeros_command:
        commands: "/tool bandwidth-test address={{ item.site_ip }} protocol=tcp direction=both user={{ item.site_user }} password={{ item.site_pass }} duration=10s"
      register: bandwidth_test_output_rc2
      with_items: "{{ csv_data_rc2.list }}" #Mengambil variabel data dari file input client sites
      ignore_errors: yes #Apabila error/client sites rto, tetap berjalan untuk test client sites berikutnya

    - name: Display raw bandwidth test results
      debug:
        var: bandwidth_test_output_rc1
      when: inventory_hostname == '172.31.254.36'

    - name: Display raw bandwidth test results
      debug:
        var: bandwidth_test_output_rc2
      when: inventory_hostname == '172.31.254.37'

    - name: Write raw bandwidth test results to a file #Menyimpan raw data hasil tes ke dalam txt
      copy:
        content: "{{ item.stdout }}"
        dest: "/tmp/bandwidth_test_raw_results_rc1_{{ item.item.site_ip }}.txt"
      with_items: "{{ bandwidth_test_output_rc1.results }}"
      when: inventory_hostname == '172.31.254.36'

    - name: Write raw bandwidth test results to a file #Menyimpan raw data hasil tes ke dalam txt
      copy:
        content: "{{ item.stdout }}"
        dest: "/tmp/bandwidth_test_raw_results_rc2_{{ item.item.site_ip }}.txt"
      with_items: "{{ bandwidth_test_output_rc2.results }}"
      when: inventory_hostname == '172.31.254.37'

    - name: Initialize averages list rcore1 #Membuat list agar dapat dibuat rata-rata dari hasil test
      set_fact:
        averages_rc1: []

    - name: Initialize averages list rcore2 #Membuat list agar dapat dibuat rata-rata dari hasil test
      set_fact:
        averages_rc2: []

    - name: Extract TX and RX averages for each site rc1 #Mengekstrak rata-rata nilai TX dan RX dari tiap client site
      set_fact:
        averages_rc1: "{{ averages_rc1 + [{'site_name': item.item.site_name, 'site_ip': item.item.site_ip, 'tx_average': item.stdout | regex_findall('tx-total-average:\\s*([0-9.]+[A-Za-z]+)') | last | default('N/A'), 'rx_average': item.stdout | regex_findall('rx-total-average:\\s*([0-9.]+[A-Za-z]+)') | last | default('N/A'), 'status_average': item.stdout | regex_findall('status:\\s*([A-Za-z ]+)') | last | default('N/A') } ] }}"
      loop: "{{ bandwidth_test_output_rc1.results }}"
      when: item.stdout is defined

    - name: Extract TX and RX averages for each site rc2 #Mengekstrak rata-rata nilai TX dan RX dari tiap client site
      set_fact:
        averages_rc2: "{{ averages_rc2 + [{'site_name': item.item.site_name, 'site_ip': item.item.site_ip, 'tx_average': item.stdout | regex_findall('tx-total-average:\\s*([0-9.]+[A-Za-z]+)') | last | default('N/A'), 'rx_average': item.stdout | regex_findall('rx-total-average:\\s*([0-9.]+[A-Za-z]+)') | last | default('N/A'), 'status_average': item.stdout | regex_findall('status:\\s*([A-Za-z ]+)') | last | default('N/A') } ] }}"
      loop: "{{ bandwidth_test_output_rc2.results }}"
      when: item.stdout is defined

    - name: Append results to CSV RC1 #Menambahkan variabel yang sudah diekstrak ke dalam report
      lineinfile:
        path: "{{ csv_filename_rc1 }}"
        line: "{{ current_timestamp }},{{ item.site_name }},{{ item.site_ip }},{{ item.tx_average }},{{ item.rx_average }},{{ item.status_average }}"
      with_items: "{{ averages_rc1 }}"

    - name: Append results to CSV RC2 #Menambahkan variabel yang sudah diekstrak ke dalam report
      lineinfile:
        path: "{{ csv_filename_rc2 }}"
        line: "{{ current_timestamp }},{{ item.site_name }},{{ item.site_ip }},{{ item.tx_average }},{{ item.rx_average }},{{ item.status_average }}"
      with_items: "{{ averages_rc2 }}"
